name: imgaug
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - alsa-lib=1.2.3=h516909a_0
  - anyio=2.2.0=py38h06a4308_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38h400218f_0
  - cfitsio=3.470=hb418390_7
  - chardet=4.0.0=py38h06a4308_1003
  - charls=2.2.0=h9c3ff4c_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.4.7=py38hd23ed53_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask-core=2021.7.2=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.7.0=pyhd8ed1ab_0
  - geos=3.9.1=h9c3ff4c_2
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - harfbuzz=2.8.2=h83ec7ef_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2021.7.30=py38hb5ce8f7_0
  - imageio=2.9.0=py_0
  - imgaug=0.4.0=py_1
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.26.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=1.900.1=h07fcdf6_1006
  - jedi=0.18.0=py38h06a4308_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyter_server=1.4.1=py38h06a4308_0
  - jupyterlab=3.1.4=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.6.2=pyhd3eb1b0_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.1=py38h1fd1430_1
  - krb5=1.19.2=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libaec=1.0.5=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.68.3=h3e27bee_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - liblapacke=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopencv=4.5.2=py38hd24989e_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libtiff=4.3.0=hf544144_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-base=3.4.2=py38hf4fb855_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nettle=3.6=he412f7d_0
  - networkx=2.3=py_0
  - notebook=6.4.2=py38h06a4308_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numpy=1.21.1=py38h9894fe3_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.2=py38h578d9bd_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py38h8e6f84c_0
  - pip=21.2.2=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-opencv=4.5.2=py38hd0cf306_1
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h5c078b8_3
  - pyyaml=5.4.1=py38h497a2fe_0
  - pyzmq=22.2.1=py38h295c915_1
  - qt=5.12.9=hda022c4_4
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scikit-image=0.18.2=py38h1abd341_0
  - scipy=1.7.1=py38h56a6a73_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38h06a4308_0
  - shapely=1.7.1=py38hb7fe4a8_5
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py38h06a4308_1
  - sqlite=3.36.0=hc218d9a_0
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tifffile=2021.8.8=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h9c3ff4c_5
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
